**Creating tensors and accessing attributes**

Tensors are the primary data structure in PyTorch and will be the building blocks for our deep learning models. They share many similarities with NumPy arrays but have some unique attributes too.

In this exercise, you'll practice creating a tensor from a Python list and displaying some of its attributes.



In [1]:
import torch

list_a = [1, 2, 3, 4]
list_b = [7, 8, 9 ,0]
# Create a tensor from list_a
tensor_a = torch.tensor(list_a)
tensor_b = torch.tensor(list_b)

print(tensor_a)

tensor([1, 2, 3, 4])


In [2]:
# Display the tensor device
print(tensor_a.device)

# Display the tensor data type
print(tensor_a.dtype)

cpu
torch.int64


**Creating tensors from NumPy arrays**

Tensors are the fundamental data structure of PyTorch. You can create complex deep learning algorithms by learning how to manipulate them.

The torch package has been imported, and two NumPy arrays have been created, named array_a and array_b. Both arrays have the same dimensions.

In [3]:
array_a = torch.tensor(list_a)
array_b = torch.tensor(list_b)

# Create two tensors from the arrays
tensor_a = torch.tensor(array_a)
tensor_b = torch.tensor(array_b)

# Subtract tensor_b from tensor_a 
tensor_c = tensor_a - tensor_b
print(tensor_c)

# Multiply each element of tensor_a with each element of tensor_b
tensor_d = tensor_a * tensor_b
print(tensor_d)

# Add tensor_c with tensor_d
tensor_e = tensor_c + tensor_d
print(tensor_e)

tensor([-6, -6, -6,  4])
tensor([ 7, 16, 27,  0])
tensor([ 1, 10, 21,  4])


/tmp/ipykernel_18/1309791693.py:5: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor_a = torch.tensor(array_a)
/tmp/ipykernel_18/1309791693.py:6: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  tensor_b = torch.tensor(array_b)


**First neural network**

We will implement a small neural network containing two linear layers. The first layer takes an eight-dimensional input, and the last layer outputs a one-dimensional tensor.

Create a neural network of linear layers that takes a tensor of dimensions 1*8
 as input and outputs a tensor of dimensions  1*1
.
Use any output dimension for the first layer you want.

In [4]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[2, 3, 6, 7, 9, 3, 2, 1]])

# Implement a small neural network with exactly two linear layers
model = nn.Sequential( nn.Linear(8,16), # Linear layer with input size 8 and output size 16
                       nn.Linear(16,1)   # Linear layer with input size 16 and output size 1

                     )

output = model(input_tensor)
print(output)

tensor([[2.0799]], grad_fn=<AddmmBackward0>)


 In practice, you'll find that modern neural networks can contain hundreds of layers and millions of parameters. Recall that the model output is not meaningful until the model is trained, i.e. until the weights and biases of each layer can meaningfully be used to produce output.

In [5]:
input_tensor = torch.Tensor(
    [[2, 3, 6, 7, 9, 3, 2, 1, 5, 3, 6, 9]]
    )

nn.Sequential(
nn.Linear(12, 20),
nn.Linear(20,14),
nn.Linear(14, 3),
nn.Linear(3, 2)
)

Sequential(
  (0): Linear(in_features=12, out_features=20, bias=True)
  (1): Linear(in_features=20, out_features=14, bias=True)
  (2): Linear(in_features=14, out_features=3, bias=True)
  (3): Linear(in_features=3, out_features=2, bias=True)
)

# The sigmoid and softmax functions

The sigmoid and softmax functions are two of the most popular activation functions in deep learning. They are both usually used as the last step of a neural network. Sigmoid functions are used for binary classification problems, whereas softmax functions are often used for multi-class classification problems. This exercise will familiarize you with creating and using both functions.

Let's say that you have a neural network that returned the values contained in the score tensor as a pre-activation output. You will apply activation functions to this output.


In [6]:
# Create a sigmoid function and apply it on input_tensor to generate a probability.
input_tensor = torch.tensor([[0.8]])

# Create a sigmoid function and apply it on input_tensor
sigmoid = nn.Sigmoid()
probability = sigmoid(input_tensor)
print(probability)

tensor([[0.6900]])


In [7]:
# Create a softmax function and apply it on input_tensor to generate a probability.

input_tensor = torch.tensor([[1.0, -6.0, 2.5, -0.3, 1.2, 0.8]])

# Create a softmax function and apply it on input_tensor
softmax = nn.Softmax(dim = -1)
probabilities = softmax(input_tensor)
print(probabilities)

tensor([[1.2828e-01, 1.1698e-04, 5.7492e-01, 3.4961e-02, 1.5669e-01, 1.0503e-01]])


# Building a binary classifier in PyTorch

Recall that a small neural network with a single linear layer followed by a sigmoid function is a binary classifier. It acts just like a logistic regression.

In this exercise, you'll practice building this small network and interpreting the output of the classifier.

Create a neural network that takes a tensor of dimensions 1x8 as input, and returns an output of the correct shape for binary classification.
Pass the output of the linear layer to a sigmoid, which both takes in and return a single float.

In [8]:
import torch
import torch.nn as nn

input_tensor = torch.Tensor([[3, 4, 6, 2, 3, 6, 8, 9]])

# Implement a small neural network for binary classification
model = nn.Sequential(
  nn.Linear(8,1),
  nn.Sigmoid()
)

output = model(input_tensor)
print(output)

tensor([[0.0377]], grad_fn=<SigmoidBackward0>)


# From regression to multi-class classification

Recall that the models we have seen for binary classification, multi-class classification and regression have all been similar, barring a few tweaks to the model.

In this exercise, you'll start by building a model for regression, and then tweak the model to perform a multi-class classification.

Create a neural network with exactly four linear layers, which takes the input tensor as input, and outputs a regression value, using any shapes you like for the hidden layers.



In [9]:
input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

# Implement a neural network with exactly four linear layers
model = nn.Sequential(nn.Linear(11,8), nn.Linear(8,16),
                      nn.Linear(16,32), nn.Linear(32,1))

output = model(input_tensor)
print(output)

tensor([[0.8927]], grad_fn=<AddmmBackward0>)


A similar neural network to the one you just built is provided, containing four linear layers; update this network to perform a multi-class classification with four outputs.

In [10]:

input_tensor = torch.Tensor([[3, 4, 6, 7, 10, 12, 2, 3, 6, 8, 9]])

model = nn.Sequential(
    nn.Linear(11, 20),
    nn.ReLU(),  # Adding ReLU activation after the first layer
    nn.Linear(20, 12),
    nn.ReLU(),  # Adding ReLU activation after the second layer
    nn.Linear(12, 6),
    nn.ReLU(),  # Adding ReLU activation after the third layer
    nn.Linear(6, 4),  # Output layer with 4 units for multi-class classification
    nn.Softmax(dim=1)  # Softmax activation to get probabilities for each class
)


output = model(input_tensor)
print(output)

tensor([[0.2929, 0.2658, 0.1826, 0.2587]], grad_fn=<SoftmaxBackward0>)


You turned your continuous regression values into probabilities bounded between zero and one by changing the output dimensions of the last linear layer, as well as by applying the softmax function.